
## 1. Pre-processing of data

```{r}
car <- data.frame(
  Country = c("U.S.","U.S.","U.S.","U.S.","U.S.","U.S.","U.S.","U.S.","U.S.","U.S.",
              "U.S.","U.S.","U.S.","U.S.","U.S.","U.S.","U.S.","U.S.","U.S.","U.S.",
              "U.S.","U.S.","U.S.","U.S.","Japan","Japan","Japan","Japan","Japan",
              "Japan","Japan","Japan","Japan","Japan","Europe","Europe","Europe","Europe"),
  Car = c("Buick Estate","Ford Country","Chevy Malibu","Chrysler LeBaron","Chevette",
          "Toyota Corona","Ford Mustang","Mazda GLC","AMC Spirit","VW Rabbit",
          "Honda Civic","Cadillac Eldorado","Chrysler NewYorker","Buick Electra",
          "Ford LTD","Chevy Caprice","Merc Marquis","Dodge StRegis","Ford Fairmont",
          "Buick Century","Olds Cutlass","Chevy Citation","Dodge Aspen","AMC Concord",
          "Datsun 210","Datsun 510","Toyota Corolla","Mazda 626","Datsun 810",
          "Toyota Cressida","Honda Accord","Datsun 200SX","VW Dasher",
          "Volvo 244DL","Peugeot 694","Renault 5","Audi 5000","Saab 99"),
  MPG = c(16.9,15.5,19.2,18.5,30.0,27.5,26.5,34.1,35.1,31.9,
          38.1,14.0,12.2,14.7,15.2,15.0,14.9,14.9,18.2,22.4,
          20.2,28.4,19.2,23.3,35.1,27.2,27.2,23.3,20.3,20.3,
          29.6,27.2,25.2,21.0,18.2,42.1,20.3,22.4),
  Weight = c(4.36,4.054,3.605,3.940,2.110,2.670,2.650,1.975,2.640,1.925,
             1.975,4.730,3.988,4.130,3.907,3.757,3.720,3.905,2.810,2.800,
             3.095,2.380,3.180,2.830,2.020,2.280,2.290,2.480,2.830,2.720,
             2.290,2.280,2.210,2.690,2.110,1.985,2.690,2.595),
  Drive_Ratio = c(2.73,2.26,2.56,2.45,3.70,3.05,3.08,3.73,2.73,3.78,
                  3.17,2.93,2.47,2.41,2.47,2.41,2.26,2.26,3.22,2.73,
                  2.41,2.69,2.71,3.08,3.70,3.70,3.91,3.55,3.70,3.58,
                  3.05,3.70,3.70,3.31,3.40,3.95,3.70,3.77),
  Horsepower = c(155,142,125,150,68,95,88,65,82,71,
                 60,145,180,155,130,130,150,155,88,110,
                 105,70,100,105,65,80,80,93,104,103,
                 68,83,79,100,77,64,100,90),
  Displacement = c(350,351,267,318,98,134,140,86,121,89,
                   91,500,440,350,302,305,351,318,200,231,
                   260,151,225,232,85,119,108,121,146,156,
                   107,119,97,163,120,79,131,108),
  Cylinders = c(8,8,8,8,4,4,4,4,4,4,
                4,8,8,8,8,8,8,8,6,6,
                6,4,6,6,4,4,4,4,6,6,
                4,4,4,6,4,4,5,4)
)
```

```{r pkg, message=F, warning=F}

# install.packages("cluster")
library(cluster)
library(tidyverse)

# First 3 observations
head(car, 3) 
```

```{r std}
# Standardize the variables by subtracting mean and divided by standard deviation
#-c(1, 2) = drop columns 1 and 2
scar = scale(car[, -c(1,2)], center=TRUE, scale=TRUE)
```

```{r}
set.seed(1)
# 3-means clustering
km = kmeans(scar, centers=3)
km
```

```{r km vis, warning=F, message=F, fig.width=5, fig.height=3.2, fig.align='center'}
install.packages("rlang")
# install.packages("factoextra")
library(factoextra)

fviz_cluster(km, data = scar, geom = "point",
             stand = FALSE, frame.type = "norm")
```

```{r hclust}
# We use the dist function in this example.
car.dist = dist(scar)
# Can also do: car.dist = daisy(scar)

# Agglomerative Hierarchical clutering
set.seed(1)
car.hclust = hclust(car.dist) # complete linkage
# Can also do: car.hclust = agnes(car.dist) 
print(car.dist)
```


```{r dendogram, fig.height=6}
# Plot dendogram
plot(car.hclust, labels=car$Car, main='Default from hclust')
# Add a horizontal line at a certain height
abline(h=6, col="red", lty=2)
abline(h=3.5, col="green", lty=2)
```

```{r cutree}
clus = cutree(car.hclust, 3)
```

```{r}
clus
```

```{r}
table(clus)
```


```{r  message = FALSE, warning = FALSE}
# install.packages("dendextend")
library(dendextend)

## dendrogram: branches colored by 3 groups
dend1 = as.dendrogram(car.hclust)
# color branches and labels by 3 clusters
dend1 = color_branches(dend1, k=3)
dend1 = color_labels(dend1, k=3)
# change label size 
dend1 = set(dend1, "labels_cex", 0.3)
```


```{r fig.align="center", fig.height=8, fig.width=5}
# add true labels to observations
dend1 = set_labels(dend1, labels=car$Car[order.dendrogram(dend1)])
# plot the dendrogram
plot(dend1, horiz=T, main = "Dendrogram colored by three clusters")
```

```{r}
s.hclust = hclust(car.dist, method = "single")

#comparing with complete linkage
table(cutree(car.hclust, k = 3), cutree(s.hclust, k = 3))

```

Complete vs single linkage- 
Rows = complete linkage clusters
Columns = single linkage clusters


-----

Credit: Adopted from <http://www.stat.berkeley.edu/classes/s133/Cluster2a.html> 